# 匹配所有分支名
'**':
  web_trigger_npm_publish:
    - imports: https://cnb.cool/qingshuPrivate/setting/-/blob/main/envs.yml
      stages:
        - name: helper发布到npmjs
          image: docker.cnb.cool/mznjs/docker/npm-sync
          settings:
            token: $NPM_TOKEN
            build: build
  web_trigger_github:
    - imports: https://cnb.cool/qingshuPrivate/setting/-/blob/main/envs.yml
      stages:
        - name: sync to github
          image: docker.cnb.cool/mznjs/docker/github-sync # #tencentcom/git-sync
          settings:
            target_url: https://github.com/MznStudio/mbump.git
            auth_type: https
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_MZN_TOKEN}
            git_user: ${GITHUB_USERNAME}
            git_email: ${GITHUB_MZN_USERMAIL}
            git_commit: false
            force_commit: true
            clear_remote: true
            branch: main
            # 仅上传以下文件/目录（逗号分隔）
            include: '.github/,src/,*.md,package.json,bin/,tests/,config-examples/,.gitignore,eslint.config.mjs,tsdown.config.ts,vitest.config.ts'
            exclude: '.git,node_modules/,*.log,Dockerfile,.env.local,tmp/,.cnb/,.cnb.yml,.trae/'
