# 匹配所有分支名
'**':
  web_trigger_npm_publish:
    - imports: https://cnb.cool/qingshuPrivate/setting/-/blob/main/envs.yml
      stages:
        - name: helper发布到npmjs
          image: docker.cnb.cool/mznjs/docker/npm-sync
          settings:
            token: $NPM_TOKEN
            mail: $USERMAIL
            folder: ./
